// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: cryptovault/v1/tron_context.proto

package cryptovaultv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TronContextV1 содержит актуальное состояние сети для построения транзакции.
// BlockID должен быть 32-байтовым идентификатором BlockNumber; предпочтительно
// использовать подтверждённый solidified-блок.
type TronContextV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockId       []byte                 `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	ExpirationMs  int64                  `protobuf:"varint,4,opt,name=expiration_ms,json=expirationMs,proto3" json:"expiration_ms,omitempty"`
	FeeLimitSun   int64                  `protobuf:"varint,5,opt,name=fee_limit_sun,json=feeLimitSun,proto3" json:"fee_limit_sun,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TronContextV1) Reset() {
	*x = TronContextV1{}
	mi := &file_cryptovault_v1_tron_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TronContextV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TronContextV1) ProtoMessage() {}

func (x *TronContextV1) ProtoReflect() protoreflect.Message {
	mi := &file_cryptovault_v1_tron_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TronContextV1.ProtoReflect.Descriptor instead.
func (*TronContextV1) Descriptor() ([]byte, []int) {
	return file_cryptovault_v1_tron_context_proto_rawDescGZIP(), []int{0}
}

func (x *TronContextV1) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *TronContextV1) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *TronContextV1) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TronContextV1) GetExpirationMs() int64 {
	if x != nil {
		return x.ExpirationMs
	}
	return 0
}

func (x *TronContextV1) GetFeeLimitSun() int64 {
	if x != nil {
		return x.FeeLimitSun
	}
	return 0
}

var File_cryptovault_v1_tron_context_proto protoreflect.FileDescriptor

var file_cryptovault_v1_tron_context_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x72, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x76, 0x61, 0x75, 0x6c, 0x74,
	0x2e, 0x76, 0x31, 0x22, 0xb9, 0x01, 0x0a, 0x0d, 0x54, 0x72, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x56, 0x31, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x66,
	0x65, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x5f, 0x73, 0x75, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x66, 0x65, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x53, 0x75, 0x6e, 0x42,
	0x54, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65,
	0x6e, 0x65, 0x67, 0x61, 0x64, 0x69, 0x6b, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2d, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x76,
	0x61, 0x75, 0x6c, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x76, 0x61,
	0x75, 0x6c, 0x74, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_cryptovault_v1_tron_context_proto_rawDescOnce sync.Once
	file_cryptovault_v1_tron_context_proto_rawDescData []byte
)

func file_cryptovault_v1_tron_context_proto_rawDescGZIP() []byte {
	file_cryptovault_v1_tron_context_proto_rawDescOnce.Do(func() {
		file_cryptovault_v1_tron_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cryptovault_v1_tron_context_proto_rawDesc), len(file_cryptovault_v1_tron_context_proto_rawDesc)))
	})
	return file_cryptovault_v1_tron_context_proto_rawDescData
}

var file_cryptovault_v1_tron_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cryptovault_v1_tron_context_proto_goTypes = []any{
	(*TronContextV1)(nil), // 0: cryptovault.v1.TronContextV1
}
var file_cryptovault_v1_tron_context_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cryptovault_v1_tron_context_proto_init() }
func file_cryptovault_v1_tron_context_proto_init() {
	if File_cryptovault_v1_tron_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cryptovault_v1_tron_context_proto_rawDesc), len(file_cryptovault_v1_tron_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cryptovault_v1_tron_context_proto_goTypes,
		DependencyIndexes: file_cryptovault_v1_tron_context_proto_depIdxs,
		MessageInfos:      file_cryptovault_v1_tron_context_proto_msgTypes,
	}.Build()
	File_cryptovault_v1_tron_context_proto = out.File
	file_cryptovault_v1_tron_context_proto_goTypes = nil
	file_cryptovault_v1_tron_context_proto_depIdxs = nil
}
