// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CryptoVaultRootSeed struct {
	Network    string
	Ciphertext []byte
	CreatedAt  pgtype.Timestamptz
}
