// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateEncryptedSeed(ctx context.Context, arg CreateEncryptedSeedParams) (string, error)
	LoadEncryptedSeed(ctx context.Context, network string) ([]byte, error)
	Ping(ctx context.Context) (int32, error)
	SeedExists(ctx context.Context, network string) (bool, error)
}

var _ Querier = (*Queries)(nil)
