// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
)

const createEncryptedSeed = `-- name: CreateEncryptedSeed :one
INSERT INTO crypto_vault.root_seeds (network, ciphertext)
VALUES ($1, $2)
ON CONFLICT (network) DO NOTHING
RETURNING network
`

type CreateEncryptedSeedParams struct {
	Network    string
	Ciphertext []byte
}

func (q *Queries) CreateEncryptedSeed(ctx context.Context, arg CreateEncryptedSeedParams) (string, error) {
	row := q.db.QueryRow(ctx, createEncryptedSeed, arg.Network, arg.Ciphertext)
	var network string
	err := row.Scan(&network)
	return network, err
}

const loadEncryptedSeed = `-- name: LoadEncryptedSeed :one
SELECT ciphertext
FROM crypto_vault.root_seeds
WHERE network = $1
`

func (q *Queries) LoadEncryptedSeed(ctx context.Context, network string) ([]byte, error) {
	row := q.db.QueryRow(ctx, loadEncryptedSeed, network)
	var ciphertext []byte
	err := row.Scan(&ciphertext)
	return ciphertext, err
}

const ping = `-- name: Ping :one
SELECT 1::integer AS alive
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var alive int32
	err := row.Scan(&alive)
	return alive, err
}

const seedExists = `-- name: SeedExists :one
SELECT EXISTS (
    SELECT 1 FROM crypto_vault.root_seeds WHERE network = $1
) AS exists
`

func (q *Queries) SeedExists(ctx context.Context, network string) (bool, error) {
	row := q.db.QueryRow(ctx, seedExists, network)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
