// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1::integer AS alive
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var alive int32
	err := row.Scan(&alive)
	return alive, err
}
