// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChainWorkerTronBlock struct {
	BlockNumber int64
	BlockID     string
	ProcessedAt pgtype.Timestamptz
}

type ChainWorkerTronScanState struct {
	Singleton       bool
	LastBlockNumber int64
	UpdatedAt       pgtype.Timestamptz
}

type ChainWorkerTronTransfer struct {
	TransactionID string
	EventIndex    int32
	BlockNumber   int64
	FromAddress   string
	ToAddress     string
	Asset         string
	Amount        pgtype.Numeric
	ObservedAt    pgtype.Timestamptz
}
