// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	AdvanceTRONScanHeight(ctx context.Context, arg AdvanceTRONScanHeightParams) (int64, error)
	CreateTRONScanState(ctx context.Context, lastBlockNumber int64) (int64, error)
	GetTRONBlockID(ctx context.Context, blockNumber int64) (string, error)
	GetTRONScanHeight(ctx context.Context) (int64, error)
	InsertTRONBlock(ctx context.Context, arg InsertTRONBlockParams) (int64, error)
	InsertTRONTransfer(ctx context.Context, arg InsertTRONTransferParams) (int64, error)
	ListTRONTransfersTo(ctx context.Context, arg ListTRONTransfersToParams) ([]ListTRONTransfersToRow, error)
}

var _ Querier = (*Queries)(nil)
