// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceTRONScanHeight = `-- name: AdvanceTRONScanHeight :execrows
UPDATE chain_worker.tron_scan_state
SET last_block_number = $1, updated_at = now()
WHERE singleton = TRUE AND last_block_number = $2
`

type AdvanceTRONScanHeightParams struct {
	LastBlockNumber   int64
	LastBlockNumber_2 int64
}

func (q *Queries) AdvanceTRONScanHeight(ctx context.Context, arg AdvanceTRONScanHeightParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceTRONScanHeight, arg.LastBlockNumber, arg.LastBlockNumber_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTRONScanState = `-- name: CreateTRONScanState :execrows
INSERT INTO chain_worker.tron_scan_state (singleton, last_block_number)
VALUES (TRUE, $1)
ON CONFLICT (singleton) DO NOTHING
`

func (q *Queries) CreateTRONScanState(ctx context.Context, lastBlockNumber int64) (int64, error) {
	result, err := q.db.Exec(ctx, createTRONScanState, lastBlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTRONBlockID = `-- name: GetTRONBlockID :one
SELECT block_id
FROM chain_worker.tron_blocks
WHERE block_number = $1
`

func (q *Queries) GetTRONBlockID(ctx context.Context, blockNumber int64) (string, error) {
	row := q.db.QueryRow(ctx, getTRONBlockID, blockNumber)
	var block_id string
	err := row.Scan(&block_id)
	return block_id, err
}

const getTRONScanHeight = `-- name: GetTRONScanHeight :one
SELECT last_block_number
FROM chain_worker.tron_scan_state
WHERE singleton = TRUE
`

func (q *Queries) GetTRONScanHeight(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTRONScanHeight)
	var last_block_number int64
	err := row.Scan(&last_block_number)
	return last_block_number, err
}

const insertTRONBlock = `-- name: InsertTRONBlock :execrows
INSERT INTO chain_worker.tron_blocks (block_number, block_id)
VALUES ($1, $2)
ON CONFLICT (block_number) DO NOTHING
`

type InsertTRONBlockParams struct {
	BlockNumber int64
	BlockID     string
}

func (q *Queries) InsertTRONBlock(ctx context.Context, arg InsertTRONBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTRONBlock, arg.BlockNumber, arg.BlockID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTRONTransfer = `-- name: InsertTRONTransfer :execrows
INSERT INTO chain_worker.tron_transfers (
    transaction_id, event_index, block_number, from_address, to_address, asset, amount
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (transaction_id, event_index) DO NOTHING
`

type InsertTRONTransferParams struct {
	TransactionID string
	EventIndex    int32
	BlockNumber   int64
	FromAddress   string
	ToAddress     string
	Asset         string
	Amount        pgtype.Numeric
}

func (q *Queries) InsertTRONTransfer(ctx context.Context, arg InsertTRONTransferParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTRONTransfer,
		arg.TransactionID,
		arg.EventIndex,
		arg.BlockNumber,
		arg.FromAddress,
		arg.ToAddress,
		arg.Asset,
		arg.Amount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTRONTransfersTo = `-- name: ListTRONTransfersTo :many
SELECT transaction_id, event_index, block_number, from_address, to_address, asset, amount::text AS amount
FROM chain_worker.tron_transfers
WHERE to_address = $1
ORDER BY block_number, transaction_id, event_index
LIMIT $2
`

type ListTRONTransfersToParams struct {
	ToAddress string
	Limit     int32
}

type ListTRONTransfersToRow struct {
	TransactionID string
	EventIndex    int32
	BlockNumber   int64
	FromAddress   string
	ToAddress     string
	Asset         string
	Amount        string
}

func (q *Queries) ListTRONTransfersTo(ctx context.Context, arg ListTRONTransfersToParams) ([]ListTRONTransfersToRow, error) {
	rows, err := q.db.Query(ctx, listTRONTransfersTo, arg.ToAddress, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTRONTransfersToRow{}
	for rows.Next() {
		var i ListTRONTransfersToRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.EventIndex,
			&i.BlockNumber,
			&i.FromAddress,
			&i.ToAddress,
			&i.Asset,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
