// Code generated by MockGen. DO NOT EDIT.
// Source: tron_invoice.go
//
// Generated by this command:
//
//	mockgen -source=tron_invoice.go -destination=../usecase/tron_invoice_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/renegadik/crypto-payment-gateway/payment-core/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTRONAddressProvider is a mock of TRONAddressProvider interface.
type MockTRONAddressProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTRONAddressProviderMockRecorder
	isgomock struct{}
}

// MockTRONAddressProviderMockRecorder is the mock recorder for MockTRONAddressProvider.
type MockTRONAddressProviderMockRecorder struct {
	mock *MockTRONAddressProvider
}

// NewMockTRONAddressProvider creates a new mock instance.
func NewMockTRONAddressProvider(ctrl *gomock.Controller) *MockTRONAddressProvider {
	mock := &MockTRONAddressProvider{ctrl: ctrl}
	mock.recorder = &MockTRONAddressProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTRONAddressProvider) EXPECT() *MockTRONAddressProviderMockRecorder {
	return m.recorder
}

// DeriveAddress mocks base method.
func (m *MockTRONAddressProvider) DeriveAddress(arg0 context.Context, arg1 uint32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeriveAddress", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeriveAddress indicates an expected call of DeriveAddress.
func (mr *MockTRONAddressProviderMockRecorder) DeriveAddress(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeriveAddress", reflect.TypeOf((*MockTRONAddressProvider)(nil).DeriveAddress), arg0, arg1)
}

// MockTRONInvoiceRepository is a mock of TRONInvoiceRepository interface.
type MockTRONInvoiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTRONInvoiceRepositoryMockRecorder
	isgomock struct{}
}

// MockTRONInvoiceRepositoryMockRecorder is the mock recorder for MockTRONInvoiceRepository.
type MockTRONInvoiceRepositoryMockRecorder struct {
	mock *MockTRONInvoiceRepository
}

// NewMockTRONInvoiceRepository creates a new mock instance.
func NewMockTRONInvoiceRepository(ctrl *gomock.Controller) *MockTRONInvoiceRepository {
	mock := &MockTRONInvoiceRepository{ctrl: ctrl}
	mock.recorder = &MockTRONInvoiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTRONInvoiceRepository) EXPECT() *MockTRONInvoiceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTRONInvoiceRepository) Create(arg0 context.Context, arg1 string, arg2 uint64, arg3, arg4 string) (domain.TRONInvoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(domain.TRONInvoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTRONInvoiceRepositoryMockRecorder) Create(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTRONInvoiceRepository)(nil).Create), arg0, arg1, arg2, arg3, arg4)
}

// FindByIdempotencyKey mocks base method.
func (m *MockTRONInvoiceRepository) FindByIdempotencyKey(arg0 context.Context, arg1 string) (domain.TRONInvoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdempotencyKey", arg0, arg1)
	ret0, _ := ret[0].(domain.TRONInvoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdempotencyKey indicates an expected call of FindByIdempotencyKey.
func (mr *MockTRONInvoiceRepositoryMockRecorder) FindByIdempotencyKey(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdempotencyKey", reflect.TypeOf((*MockTRONInvoiceRepository)(nil).FindByIdempotencyKey), arg0, arg1)
}

// GetWithTransfers mocks base method.
func (m *MockTRONInvoiceRepository) GetWithTransfers(arg0 context.Context, arg1 string) (domain.TRONInvoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithTransfers", arg0, arg1)
	ret0, _ := ret[0].(domain.TRONInvoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithTransfers indicates an expected call of GetWithTransfers.
func (mr *MockTRONInvoiceRepositoryMockRecorder) GetWithTransfers(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithTransfers", reflect.TypeOf((*MockTRONInvoiceRepository)(nil).GetWithTransfers), arg0, arg1)
}

// NextAddressIndex mocks base method.
func (m *MockTRONInvoiceRepository) NextAddressIndex(arg0 context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextAddressIndex", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextAddressIndex indicates an expected call of NextAddressIndex.
func (mr *MockTRONInvoiceRepositoryMockRecorder) NextAddressIndex(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextAddressIndex", reflect.TypeOf((*MockTRONInvoiceRepository)(nil).NextAddressIndex), arg0)
}
